server:
  port: 8099
  shutdown: immediate

spring:
  application:
    name: templet
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./log/db.db
  jackson:
    default-property-inclusion: always
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mybatis:
    web:
      max-page-size: 100
      page-parameter: page
      size-parameter: size
      default-page-size: 10

logging:
  file.name: ./log/log.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) [%clr(%thread){blue}] - %cyan(%logger{50}) : %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] - %logger{50} : %line - %msg%n'
  level:
    root: info
    org.springframework: warn

mybatis-plus:
  global-config:
    db-config:
      #主键类型  AUTO :"数据库ID自增", INPUT :"用户输入ID",ID_WORKER :"全局唯一ID (数字类型唯一ID)",
      #ID_WORKER_STR :"字符串全局唯一ID"  UUID :"全局唯一ID UUID" NONE: 该类型为未设置主键类型
      id-type: NONE
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 查看 SQL 执行日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
